apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment-app1
  template:
    metadata:
      labels:
        app: assessment-app1
    spec:
      containers:
        - name: assessment-app1
          image: swathiwohlig/assessment-app1:latest1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001